from __future__ import annotations

from typing import Any, Dict, List

from scriptkiddie_core.models import Finding

_SEV_ICON = {"critical": "!!!", "high": "!!", "medium": "!", "low": "."}


def to_markdown(findings: List[Finding], job_meta: Dict[str, Any] | None = None) -> str:
    lines: list[str] = []
    meta = job_meta or {}

    lines.append("# Script-Kiddie Scan Report")
    lines.append("")
    if meta:
        if meta.get("target"):
            lines.append(f"**Target:** `{meta['target']}`")
        if meta.get("ruleset"):
            lines.append(f"**Ruleset:** `{meta['ruleset']}`")
        if meta.get("decision"):
            lines.append(f"**Decision:** `{meta['decision']}`")
        lines.append("")

    lines.append(f"**Total findings:** {len(findings)}")
    lines.append("")

    # Summary table
    sev_counts: Dict[str, int] = {}
    for f in findings:
        sev_counts[f.severity] = sev_counts.get(f.severity, 0) + 1

    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ["critical", "high", "medium", "low"]:
        if sev in sev_counts:
            lines.append(f"| {sev} | {sev_counts[sev]} |")
    lines.append("")

    # Findings detail
    if findings:
        lines.append("## Findings")
        lines.append("")
        for f in findings:
            icon = _SEV_ICON.get(f.severity, "?")
            lines.append(f"### [{f.severity.upper()}] {f.title}")
            lines.append("")
            lines.append(f"- **Rule:** `{f.rule_id}`")
            lines.append(f"- **File:** `{f.file}:{f.line}`")
            if f.cwe_ids:
                lines.append(f"- **CWE:** {', '.join(f.cwe_ids)}")
            if f.owasp_ids:
                lines.append(f"- **OWASP:** {', '.join(f.owasp_ids)}")
            lines.append(f"- **Match:** `{f.match[:100]}`")
            if f.message:
                lines.append(f"- **Message:** {f.message}")
            if f.remediation:
                lines.append(f"- **Remediation:** {f.remediation}")
            lines.append("")

    lines.append("---")
    lines.append("*Generated by Script-Kiddie*")
    return "\n".join(lines)
